name: Build Document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set Up Git Repository
        uses: actions/checkout@v3
      - name: Compile Questions Document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.questions.tex
          latexmk_use_xelatex: true
      - name: Compile Solution Document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.solution.tex
          latexmk_use_xelatex: true
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Assignment
          path: |
            main.questions.pdf
            main.solution.pdf
